services:
  mariadb:
    image: mariadb:10.11.14
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      bosskills:
        ipv4_address: 172.99.0.2
    command:
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --max_allowed_packet=256M
      - --connect_timeout=60
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    volumes:
      - dragonfly-data:/data
    networks:
      bosskills:
        ipv4_address: 172.99.0.3
volumes:
  mariadb-data:
  dragonfly-data:
networks:
  bosskills:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/24
          gateway: 172.99.0.1
