version: '3.4'
services:
  mariadb:
    image: mariadb:11.1
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      bosskills:
        ipv4_address: 172.19.0.2
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    volumes:
      - dragonfly-data:/data
    networks:
      bosskills:
        ipv4_address: 172.19.0.3
volumes:
  mariadb-data:
  dragonfly-data:
networks:
  bosskills:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
